# Generated by Django 3.1.7 on 2021-03-04 15:12

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('body', models.TextField(blank=True)),
                ('pub_date', models.DateField(default='03-04')),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
    ]
