# Generated by Django 3.1.7 on 2021-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='type_of_story',
            field=models.CharField(choices=[('dream', 'Dream'), ('nightmare', 'Nightmare')], default='dream', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateField(default='03-05-21'),
        ),
    ]
